version: '3'
services:
  database:
    image: postgres:12-alpine
    #restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mq:
    #image: rabbitmq:3-alpine
    image: rabbitmq:3-management-alpine
    #restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=karnickel
      - RABBITMQ_DEFAULT_PASS=hasehuepf
    ports:
      - 5672:5672
      - 9080:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  backend:
    #image: docker.pkg.github.com/doerfli/iwashere/iwashere-backend:master
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/postgres
      - SPRING_RABBITMQ_HOST=mq
      - SPRING_RABBITMQ_USERNAME=karnickel
      - SPRING_RABBITMQ_PASSWORD=hasehuepf
      - SPRING_REDIS_HOST=redis
      - MAILGUN_APIKEY=1234567890
    depends_on:
      - database
      - mq
      - redis
  frontend:
    #image: docker.pkg.github.com/doerfli/iwashere-web/iwashere-frontend:master
    build: ../iwashere-web
    ports:
      - 8888:80
    depends_on:
      - backend
