version: '3'
services:
  database:
    image: postgres:12-alpine
    #restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    image: docker.pkg.github.com/doerfli/iwashere/iwashere-backend:master
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/postgres
      - MAILGUN_APIKEY=1234567890
  frontend:
    image: docker.pkg.github.com/doerfli/iwashere-web/iwashere-frontend:master
    ports:
      - 8888:80
