version: '3'
services:
  database:
    image: postgres:12-alpine
    #restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    image: iwashere
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/postgres
  frontend:
    image: iwashere-web
    ports:
      - 8888:80
