#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.secure=true
logging:
  level:
    li:
      doerf: DEBUG
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

spring:
  datasource:
    username: postgres
    password: secret
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    port: 5672
    username: karnickel
    password: hasehuepf
  cloud:
    stream:
      bindings:
        mailIn:
          binder: rabbit
          destination: mails
          group: input-group-1
        mailOut:
          binder: rabbit
          destination: mails
          group: output-group-1

server:
  servlet:
    contextPath: /api

mailgun:
  apikey: ${MAILGUN_APIKEY}
  baseurl: https://api.mailgun.net/v3/mail.bytes.li

baseUrl: http://localhost:8081
mailsender: info@mail.ich-war-da.net

cleanup:
  cron: "0 3 0 * * *"
  retentionDays: 15
